name:                IF686-PacMan
version:             0.1.0.0
github:              "githubuser/IF686-PacMan"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/IF686-PacMan#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- extra
- sdl2
- sdl2-image
- sdl2-mixer
- stm
- text

library:
  source-dirs: src

executables:
  IF686-PacMan-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IF686-PacMan

tests:
  IF686-PacMan-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - IF686-PacMan
